<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Wishlist block customer item cart column
 *
 * @author      Magento Core Team <core@magentocommerce.com>
 */
namespace Singh\Wishlist\Block\Customer\Wishlist\Item\Column;

use Magento\Framework\Stdlib\DateTime\TimezoneInterface;
use Magento\Catalog\Block\Product\Context;
use Magento\Framework\Pricing\Render;

class Image extends \Magento\Wishlist\Block\Customer\Wishlist\Item\Column
{
    protected $timeZoneInterface;
    protected $priceRender;
    public function __construct(
        Context $context,
        Render $render,
        TimezoneInterface $timezoneInterface,
        \Magento\Framework\App\Http\Context $httpContext,        
        array $data)
    {
        parent::__construct($context, $httpContext, $data);
        $this->timeZoneInterface = $timezoneInterface;
        $this->priceRender = $render;
    }

    /**
     * @param $addedDate
     * @return string
     */
    public function getWishlistAddedAt($addedDate){
        return $this->timeZoneInterface->formatDate($addedDate,\IntlDateFormatter::LONG,false);
    }

    /**
     * Returns qty to show visually to user
     *
     * @param \Magento\Wishlist\Model\Item $item
     * @return float
     */
    public function getAddToCartQty(\Magento\Wishlist\Model\Item $item)
    {
        $qty = $item->getQty();
        return $qty ? $qty : 1;
    }

    /**
     * Return product for current item
     *
     * @return \Magento\Catalog\Model\Product
     */
    public function getProductItem()
    {
        return $this->getItem()->getProduct();
    }
    
    public function getProductPriceHtml(
        \Magento\Catalog\Model\Product $product,
        $priceType,
        $renderZone = \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
        array $arguments = []
    )
    {
        return parent::getProductPriceHtml($product, $priceType, $renderZone, $arguments); // TODO: Change the autogenerated stub
    }

}
