<div class="inner-page">
    <div class="container no_pad">      
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 static-pages">          
        <h2>Wish List<span>Agreement</span></h2>
          <h3>Terms of Use</h3>
<p>The following are the terms and conditions for use of the Camping World, Inc. Wish List. Please read them carefully. By using or accessing the Wish List, you agree to these terms. You may not use the Wish List if you do not agree to these terms of use.</p>

<h3>Member Registration</h3>
<p>In order to use this service, you must create a free Camping World Online account and are subject to the terms and conditions of the Camping World, Inc. website. The Wish List is intended for Camping World Online customers only. The feature is designed to enable people to select products they would like others to purchase for them. Wishlists are designed to be shared for shopping convenience and for no other purpose. You agree not to use the information made available in the Wish List to abuse, threaten, or harass another person. Children under 13 years of age may not use the Wish List.</p>

<h3>Use Of Your Friends And Family eMail Addresses</h3>
<p>If you give us the eMail address of your family and friends, we will use their eMail addresses only to send them a copy of your wish list. Their eMail addresses will not be used for any other purpose.</p>

<h3>Use Of Your eMail Address</h3>
<p>By choosing to send your wish list to our friends and family, you authorize Camping World, Inc. to use your eMail address to send your list to them.</p>

<h3>No Spam, Damages</h3>
<p>Camping World, Inc. will immediately terminate any account of any person that it believes, in its sole discretion, is using the Wish List in connection with any spam or other unsolicited bulk eMail or using the Wish List to harass or to send unwanted communications. In such instance, Camping World, Inc. shall have the right to an injunction and to seek monetary damages.</p>

<h3>Indemnification</h3>
<p>You agree to indemnify Camping World, Inc., its parents, subsidiaries, affiliates, officers, directors, shareholders and employees for any claim, including payment of reasonable attorney’s fees, asserted by any third party arising from any misuse of the Wish List by you.</p>

<h3>Unauthorized Use By Third Parties</h3>
<p>Camping World, Inc. shall not be liable or responsible for misuse by third parties of information that you or other users choose to publish on our web site, including, your name, mailing address, eMail address, other personal information and product preferences.</p>

<h3>Availability Of Wish List Information</h3>
<p>You may make your wish list searchable making it easier for your friends and family to find your wish list. By making your wish list searchable, any Camping World Online shopper can locate your list by searching for your eMail address. If you choose not to make your wish list searchable, we will help you send an eMail message to your friends and family with instructions on how to find it.</p>                    
        </div>            
    </div>
</div>