<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
//$addedAt = $block->getA
?>
<h3>ADDED <?php echo $block->getWishlistAddedAt($item->getAddedAt())?></h3>
<a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($item) ?>" title="<?php echo $block->escapeHtml($product->getName()) ?>">
    <?php echo $block->getImage($product, 'wishlist_thumbnail')->toHtml(); ?>
</a>
