<?php
$item = $block->getItem();
$product = $item->getProduct();
?>
<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
?>
<!---->
<?php //foreach ($block->getChildNames() as $childName): ?>
<!--    --><?php ///* @escapeNotVerified */ echo $block->getLayout()->renderElement($childName, false); ?>
<?php //endforeach;?>

<?php
$priceBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
//getting $product object, passed $product object inside function
echo $priceBlock->getProductPrice($product);
?>