<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
?>
    <?php $iterator = 1; ?>
    <?php if (count($block->getItems())): ?>
        <ul class="clearfix">
            <?php foreach ($block->getItems() as $item): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="col-sm-12 col-md-6 col-lg-6" data-row="product-item" id="item_' . $item->getId() . '">' : '</li><li class="col-sm-12 col-md-6 col-lg-6" id="item_' . $item->getId() . '">' ?>
                    <?php foreach ($columns as $column): ?>
                        <?php $column->setItem($item); echo $column->toHtml($item);?>
                    <?php endforeach; ?>
                <?php echo($iterator == count($block->getItems())+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <div class="message info empty">
            <span><?php /* @escapeNotVerified */ echo __('This Wish List has no Items');?></span>
        </div>
    <?php endif; ?>
<?php foreach ($columns as $column): ?>
    <?php echo $column->getAdditionalHtml();?>
<?php endforeach; ?>